In [111]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

predict marks of student bassed on hrs_stuied,iq,city,hrs_slept


In [112]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



In [113]:
#creating data set
np.set_printoptions(precision = 2)
df =pd.DataFrame(np.random.rand(50,3)*10,columns = 'hrs_studied hrs_slept IQ'.split())
from random import choice
city = []
for i in range(50):
    c = choice(['pune','mumbai','banglore'])
    city.append(c)
    
df['city']=city  

df.head()



hrs_studied  hrs_slept        IQ      city
0     2.229335   6.439354  4.139597    mumbai
1     2.819743   6.675484  0.968367    mumbai
2     5.294096   9.488198  8.158760  banglore
3     4.802506   1.286728  2.161443      pune
4     2.577076   8.207169  0.289113    mumbai

In [114]:
#creating dependent variable marks
df['marks'] = 1.29 + (3.45*df['hrs_studied']) + (2.56*df['hrs_slept']) + (1.98*df['IQ'])
df['marks'] = df['marks'] + np.random.rand(50)*20

df.head()


hrs_studied  hrs_slept        IQ      city      marks
0     2.229335   6.439354  4.139597    mumbai  44.445659
1     2.819743   6.675484  0.968367    mumbai  35.167167
2     5.294096   9.488198  8.158760  banglore  76.300956
3     4.802506   1.286728  2.161443      pune  27.979848
4     2.577076   8.207169  0.289113    mumbai  41.383824

In [115]:
#encoding non int data
np.set_printoptions(precision = 2)
X = df.values[:,:-1]
y = df.values[:,-1]
X

array([[2.2293350314982097, 6.439353718221637, 4.139596949107044,
        'mumbai'],
       [2.819742617496935, 6.675484402319465, 0.9683670349071016,
        'mumbai'],
       [5.294095973502101, 9.48819790910664, 8.158760317974211,
        'banglore'],
       [4.802505557504229, 1.2867276756010448, 2.1614429561559643,
        'pune'],
       [2.5770760439122578, 8.207169425048413, 0.289113263888513,
        'mumbai'],
       [1.7564378792022173, 3.11048771944208, 8.92705288167404, 'mumbai'],
       [3.480411865709762, 2.457648430125224, 7.017053371327625,
        'mumbai'],
       [1.5651670178170562, 5.660437330969205, 5.047210897461043,
        'banglore'],
       [7.809413723213467, 9.628223932057121, 5.617525233292354, 'pune'],
       [5.128474362765027, 6.079987566850425, 2.6377291172181905, 'pune'],
       [7.276512308529494, 9.327223242787872, 6.481144186809921,
        'mumbai'],
       [7.881613549715507, 1.8611808265551544, 0.2959785664879455,
        'banglore'],
       [4

In [116]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[3])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)


[[0.0 1.0 0.0 2.2293350314982097 6.439353718221637 4.139596949107044]
 [0.0 1.0 0.0 2.819742617496935 6.675484402319465 0.9683670349071016]
 [1.0 0.0 0.0 5.294095973502101 9.48819790910664 8.158760317974211]
 [0.0 0.0 1.0 4.802505557504229 1.2867276756010448 2.1614429561559643]
 [0.0 1.0 0.0 2.5770760439122578 8.207169425048413 0.289113263888513]
 [0.0 1.0 0.0 1.7564378792022173 3.11048771944208 8.92705288167404]
 [0.0 1.0 0.0 3.480411865709762 2.457648430125224 7.017053371327625]
 [1.0 0.0 0.0 1.5651670178170562 5.660437330969205 5.047210897461043]
 [0.0 0.0 1.0 7.809413723213467 9.628223932057121 5.617525233292354]
 [0.0 0.0 1.0 5.128474362765027 6.079987566850425 2.6377291172181905]
 [0.0 1.0 0.0 7.276512308529494 9.327223242787872 6.481144186809921]
 [1.0 0.0 0.0 7.881613549715507 1.8611808265551544 0.2959785664879455]
 [0.0 1.0 0.0 4.635193069562071 7.698433998880625 1.8324453386546402]
 [0.0 1.0 0.0 6.562733773055748 0.7914922744722508 6.5229021352985725]
 [1.0 0.0 0.0 2.59564179

In [117]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)


In [118]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [119]:
y_pred = regressor.predict(X_test)
y_pred

array([43.97, 44.91, 71.02, 74.92, 72.18, 23.63, 43.65, 30.93, 66.47,
       40.79])

In [120]:
y_test

array([40.08336723612916, 50.10737538427165, 72.02649060722018,
       82.09889989046505, 76.30095589463258, 18.73745106630497,
       48.87500276463814, 36.13329433604433, 75.34942922409817,
       41.38382444526253], dtype=object)

In [122]:
df_results =pd.DataFrame({'test':y_test,'predicted':y_pred})
df_results

test  predicted
0  40.083367  43.974297
1  50.107375  44.909170
2  72.026491  71.015626
3    82.0989  74.921496
4  76.300956  72.180169
5  18.737451  23.628323
6  48.875003  43.649913
7  36.133294  30.925805
8  75.349429  66.472760
9  41.383824  40.794843

In [126]:
from sklearn.metrics import accuracy_score
cf= accuracy_score(y_test,y_pred)

ValueError: Classification metrics can't handle a mix of unknown and continuous targets